# Generated by Django 5.2 on 2025-05-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
