# Generated by Django 5.2 on 2025-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmonitor',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urlmonitor',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
