# Generated by Django 5.2 on 2025-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_urlmonitor_is_failed_urlmonitor_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('palabras', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='filtros/')),
            ],
        ),
    ]
