# Generated by Django 5.2 on 2025-05-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_filtro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('palabras', models.TextField()),
            ],
        ),
    ]
